# Exclude test gemfiles and lib/aws-sdk-rails from snake_case naming.
# The lib/aws-sdk-rails.rb file must not be snake_cased or else
# `Bundler.require(*Rails.groups)` in Rails applications will not automatically
# load our gem.
Naming/FileName:
  Exclude:
    - 'gemfiles/*.gemfile'
    - 'lib/sqs_consumer.rb'

# Allow the $VERSION global variable.
# Ideally we shouldn't use any global variables, but here we are.
Style/GlobalVars:
  AllowedVariables:
    - $VERSION
